### ISSUE TITLE
Debian py2exe

### ISSUE THREAD

**Issue by dudemax** [jpdias/botnet-lab#5]
Found out that some/all Linux users can't install py2exe module through pip
Also I faced with some problems when I tried to install this module through setup.py
Can you give some clue for me?

**Comment by jpdias** [comment]
Py2exe is only used to turn the Python code into executable Windows programs, so it's not compatible with Linux. However, this module is not required to the use of the lab, and this requirement can be ignored.

**Comment by dudemax** [comment]
Can U advice some alternative?)
